services:
  jenkins:
    image: docker.io/jenkins/jenkins:alpine-jdk21
    restart: unless-stopped
    security_opt:
      - label=type:container_runtime_t
    volumes:
      - jenkins_home:/var/jenkins_home
      - ${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock:z
    networks:
      - hbnet
    ports:
      - '8080:8080'

volumes:
  jenkins_home:

networks:
  hbnet:
    external: true
