services:
  nginx:
    image: docker.io/library/nginx:alpine-otel
    restart: unless-stopped
    security_opt:
      - label=type:container_runtime_t
    volumes:
      - ./config/nginx:/etc/nginx:z,ro
    networks:
      - hbnet
    ports:
      - '8880:80'

networks:
  hbnet:
    external: true
