services:
  otel:
    image: docker.io/otel/opentelemetry-collector-contrib:latest
    restart: unless-stopped
    security_opt:
      - label=type:container_runtime_t
    volumes:
      - ./config/otel:/etc/otelcol-contrib:z,ro
    networks:
      - hbnet
    ports:
      - '1777:1777' # pprof extension
      - '8888:8888' # Prometheus metrics exposed by the Collector
      - '8889:8889' # Prometheus exporter metrics
      - '13133:13133' # health_check extension
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP http receiver
      - '55679:55679' # zpages extension

networks:
  hbnet:
    external: true
