services:
  postgres:
    image: docker.io/library/postgres:alpine
    restart: unless-stopped
    shm_size: 256m
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - hbnet
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_USER: admin
      POSTGRES_DB: hb-db

volumes:
  pg_data:

networks:
  hbnet:
    external: true
