services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    restart: unless-stopped
    security_opt:
      - label=type:container_runtime_t
    volumes:
      - prom_data:/prometheus
      - ./config/prometheus:/etc/prometheus:z,ro
      - ${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock:z
    networks:
      - hbnet
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  prom_data:

networks:
  hbnet:
    external: true
