services:
  rabbitmq:
    image: docker.io/library/rabbitmq:management-alpine
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - hbnet
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: P@ssw0rd

volumes:
  rabbitmq_data:
    
networks:
  hbnet:
    external: true
