services:
  vault:
    image: docker.io/hashicorp/vault:latest
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_log:/vault/logs
      - vault_file:/vault/file
      - vault_config:/vault/config.d
    networks:
      - hbnet
    ports:
      - '8200:8200'
    environment:
      VAULT_ADDR: 'http://localhost:8200'
      VAULT_LOCAL_CONFIG: |
        {
          "ui": true,
          "listener": [
            {
              "tcp": {
                "address": "0.0.0.0:8200",
                "tls_disable": true
              }
            }
          ],
          "storage": {
            "file": {
              "path": "/vault/file"
            }
          },
          "api_addr": "http://localhost:8200",
          "disable_mlock": true
        }
    command: server

volumes:
  vault_file:
  vault_log:
  vault_config:

networks:
  hbnet:
    external: true
