extensions:
  health_check:
    endpoint: otel:13133
  pprof:
    endpoint: otel:1777
  zpages:
    endpoint: otel:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel:4317
      http:
        endpoint: otel:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 10s
          static_configs:
            - targets: [localhost:8888]

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128
  probabilistic_sampler:
    hash_seed: 22
    sampling_percentage: 15
  batch:
    send_batch_size: 8192
    send_batch_max_size: 0
    timeout: 10s

exporters:
  debug:
    verbosity: basic
  prometheus:
    endpoint: otel:8889
    namespace: default

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, probabilistic_sampler, batch]
      exporters: [debug]
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, batch]
      exporters: [debug, prometheus]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]